" gvimrc

" colorscheme & UI
set guifont=Menlo:h15

" rspec.vim
let g:rspec_command = "bundle exec rspec {spec}" " cannot use Dispatch

" Use Cmd + P for fzf
map <D-p> :Files<cr>

if has('gui_macvim')
  " This removes the Cmd-P binding from 'Print':
  macmenu &File.Print key=<nop>
endif
