" ======= Mappings =======
" Leader key
let mapleader = "\<Space>"

" Always jump to first non blank character
nmap 0 ^

" Write the file with Ctrl-s
nmap <C-s> :w<cr>
imap <C-s> <esc>:w<cr>

" Move up and down by visible lines if current line is wrapped 
nmap j gj
nmap k gk

" Rapid editing of vimrc
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

" Ain't nobody got time for Esc
imap jk <esc>
imap kj <esc>

" ======= Options =======
set number
set nocompatible
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set ruler		       " show the cursor position all the time
set splitbelow                 " Open new split panes to bottom
set splitright                 " Open new split panes to right
set directory=~/.tmp           " Don't clutter dirs up with swp and tmp files
