# ----- Settings & Options -----
# Path to your dotfiles
export DOTFILES=$HOME/.dotfiles

export VISUAL=nvim
export EDITOR="$VISUAL"

# Homebrew: Only update explicitely required packages
export HOMEBREW_NO_AUTO_UPDATE=1

# Setting fd as the default source for fzf (thus respecting .gitignore)
export FZF_DEFAULT_COMMAND='ag -g ""'

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Timestamp shown in the history command output - cf. 'man strftime'
HIST_STAMPS="yyyy-mm-dd"

# Disable auto-highlight of pasted content
zle_highlight=('paste:none')

# ----- Prompt -----
# https://github.com/spaceship-prompt/spaceship-prompt
autoload -U promptinit; promptinit
prompt spaceship
SPACESHIP_GIT_STATUS_COLOR="172"

# ----- Functions -----
source $DOTFILES/zsh/functions.zsh

# ----- Aliases -----
source $DOTFILES/zsh/aliases.zsh

# ----- Plugins -----

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
